### ISSUE TITLE
1.20 Issue Tracker / Generic 

### ISSUE THREAD

**Issue by TheMeinerLP** [TheMeinerLP/FastAsyncWorldEdit#1]
Schema: Class Code Comment
1.20 related:
- [ ] PaperweightMapChunkUtil TWO_MEGABYTES looks odd
- [ ] Material Changes

Generic:
- [ ] Logger parent issue
- [ ] Spigot / Mojang mapping improvements
- [ ] SimpleBlockMaterial usage

**Comment by hkkongou** [comment]
hi, may i ask is there any 1.20 folia FAWE jar?
thx

**Comment by TheMeinerLP** [comment]
Not yet also not planned on my timetable
